substitutions:
  devicename: example
  upper_devicename: Example

  # pins for fowards and backwards, invert as necessary
  pin_motor_a: D5
  pin_motor_b: D6

  pin_switch_limit: D1

  open_duration: 1min
  close_duration: 0.9min
  # MUST be greater than open_duration and close_duration (not combined)
  max_duration: 1.1min

esp8266:
  board: nodemcuv2

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$upper_devicename"
    password: !secret wifi_password

captive_portal:

# Enable logging
# logger:

# Enable Home Assistant API
# api:
#   password: !secret api_password

# Enable local web interface
# web_server:
#   port: 80
#   ota: false

<<: !include ../src/motor.yaml
